### ISSUE TITLE
strange effect on windows?

### ISSUE THREAD

**Issue by 3k2** [L4ki/Infinity-Plasma-Themes#1]
Hey,

after updating the theme yesterday I am now getting this strange effect on windows seems to be going away after changing theme to another but comes back when changing to infinity.

![image](https://user-images.githubusercontent.com/11908261/101980970-ec65d600-3c71-11eb-939d-bf0f6312c175.png)

**Comment by 3k2** [comment]
I also tried to install it again from plasma global themes 

`Installation of /tmp/LJkMsH-Infinity-Global.zip failed: Could not install dependency: 'kns://icons.knsrc/api.kde-look.org/1436567'`

**Comment by L4ki** [comment]
Hi 3k2,

I think the problem is in the cache
Clean the cach with Bleachbit, or manually.
I do it manually, see screenshot: https://postimg.cc/zbnpTnvz
Dolphin (Show Hidden Files)> Home> .cache
So all these "kcache" files.
Do not delete folders!
Logout or restart.

Please let me know if it's ok.

P.S.

I have Window Decorations, set up like this: https://postimg.cc/ygz2q6SN

As for downloading Global Theme from System Settings, I just downloaded it from "Virtual Machine" without any problems.
I did the check ten minutes ago.

Screenshot with "Virtual Machine": https://postimg.cc/0rj0kRd5

**Comment by 3k2** [comment]
Hey, does this look correct to you? I don't remember exactly where the borders suppose to be less transparent or not?

![image](https://user-images.githubusercontent.com/11908261/101991919-85b7db00-3cb8-11eb-8d25-0f71ad7dfe91.png)
![image](https://user-images.githubusercontent.com/11908261/101991936-a1bb7c80-3cb8-11eb-99e3-beb3374075af.png)

here's my settings:

![image](https://user-images.githubusercontent.com/11908261/101991954-b5ff7980-3cb8-11eb-9c8d-72765b88c12c.png)
![image](https://user-images.githubusercontent.com/11908261/101991963-c44d9580-3cb8-11eb-917d-b83ab8a6e561.png)
![image](https://user-images.githubusercontent.com/11908261/101991968-ce6f9400-3cb8-11eb-8960-4e2285b6ec6d.png)

**Comment by L4ki** [comment]
Hi 3k2,

It's better now, but it's not as it should be.

This is how it is with me:

https://postimg.cc/PN3n0L1q

https://postimg.cc/mPMxc8Jc

https://postimg.cc/DWK9113x

The only thing I can suggest is:

Set to System Settings> Application Style> Window Decorations,

as in this screenshot: https://postimg.cc/DWK9113x

Use themes default window border size (Do not mark), and
set No Borders

**Comment by 3k2** [comment]
![image](https://user-images.githubusercontent.com/11908261/103404467-57614900-4b5c-11eb-8522-765dbca5fd5b.png)

after yesterdays update it for some reason disappeared from my installed themes and now fails to install :/

**Comment by L4ki** [comment]
Hi 3k2,

Thanks for the info.

I installed "Infinity-Global" in Virtualbox, no problem. (openSUSE Tumbleved Plasma 5.20.4)

Then I switched to openSUSE Leap 15.2 (Plasma 5.18.6)
Installs everything except Infinity-Dark-Icons

Something strange is happening, I don't understand.

Please try again.

If it's not a problem, let me know if it's okay or not.

**Comment by 3k2** [comment]
> Hi 3k2,
> 
> Thanks for the info.
> 
> I installed "Infinity-Global" in Virtualbox, no problem. (openSUSE Tumbleved Plasma 5.20.4)
> 
> Then I switched to openSUSE Leap 15.2 (Plasma 5.18.6)
> Installs everything except Infinity-Dark-Icons
> 
> Something strange is happening, I don't understand.
> 
> Please try again.
> 
> If it's not a problem, let me know if it's okay or not.

I managed to install it but I don't know what I did.. something I did..

btw how do you set the color correctly to firefox for example? when I press mouse 2 in firefox on any webpage the highlight color is blue not green like in the address bar. I did install the infinity gtk theme as well and set it in the settings too but it didn't have any effect. Tho I had to do it manually since the kde downloader for gtk/gnome themes isn't working for whatever reason..

thanks for your efforts!

**Comment by L4ki** [comment]
Hi 3k2,

Firefox has a color scheme depending on which Colorscheme is set, in this case "Infinity-Dark-Color".

Colorscheme "Infinity-Dark-Color" has that blue color for "Focus-Decoration" and the color uFirefox depends on it.

The complete Theme is a combination of these colors.

If you want that color to be the same (Dark cyan - # 08a19d), you have to change the color to the "Infinity-Dark-Color" color scheme, like this:

Original: https://postimg.cc/4YP6CdQV

Modified: https://postimg.cc/z3wkN85z

Let me know if it worked.

Greeting,
