### ISSUE TITLE
Window Decorations disappear when app is maximized on Garuda

### ISSUE THREAD

**Issue by famewolf** [L4ki/Infinity-Plasma-Themes#2]
I prefer the infinity windows decorations however when an app is maximized (firedragon in my example screenshots) the area where the min/max/close normally appears is blank.  The one that works is garuda's default "sweet" theme and windows decorations.   Examples follow:

![Screenshot_20241006_123318](https://github.com/user-attachments/assets/f60f6c05-eb05-4daa-9c17-08f4ae91dce9)
![Screenshot_20241006_123459](https://github.com/user-attachments/assets/e886b786-8dfe-4858-888e-815d7318a4af)

**Comment by L4ki** [comment]
Hi famewolf, 

I installed "Firedragon" browser, and everything is ok.

Screenshot: [![Screenshot-20241007-094244.png](https://i.postimg.cc/pTQbfM6w/Screenshot-20241007-094244.png)](https://postimg.cc/LYsbSwRD)

**Comment by famewolf** [comment]
Apologies.  Apparently Garuda has "windows buttons" (have to right click the blank area) that also have to be set and those are what appear in firedragon when maximized so now I have them in both places!   Thank you for looking into it..
